# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    ignore:
      - dependency-name: "@monorepo/eslint-config"
      - dependency-name: "@monorepo/tsconfig"
    labels:
      - "dependencies"
      - "root"

#  - package-ecosystem: "npm"
#    directory: "/packages/inquirer"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 10
#    versioning-strategy: "auto"
#    labels:
#      - "dependencies"
#      - "inquirer"
#
#  - package-ecosystem: "npm"
#    directory: "/packages/discordjs-adaptor"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 10
#    versioning-strategy: "auto"
#    labels:
#      - "dependencies"
#      - "discordjs-adaptor"

